// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ChromaEdge_CharacterAffinity","status":true,"description":"v0.1.0 Chroma's Edge affinity tracking foundation.","parameters":{"minAffinity":"1","maxAffinity":"10","defaultAffinity":"1","dlbRequiredAffinity":"10"}},
{"name":"ChromaEdge_SummonSystem","status":false,"description":"v0.1.0 Week 1 stub: Summon system.","parameters":{}},
{"name":"ChromaEdge_DualLimitBreak","status":false,"description":"v0.1.0 Week 1 stub: Dual Limit Break.","parameters":{}},
{"name":"ChromaEdge_QuestSystem","status":false,"description":"v0.1.0 Week 1 stub: Quest system.","parameters":{}},
{"name":"ChromaEdge_DialogueTree","status":false,"description":"v0.1.0 Week 1 stub: Dialogue tree.","parameters":{}},
{"name":"ChromaEdge_DayNightSystem","status":false,"description":"v0.1.0 Week 1 stub: Day/night.","parameters":{}},
{"name":"ChromaEdge_NPCScheduling","status":false,"description":"v0.1.0 Week 1 stub: NPC scheduling.","parameters":{}},
{"name":"ChromaEdge_MercyChoiceSystem","status":false,"description":"v0.1.0 Week 1 stub: Mercy choices.","parameters":{}},
{"name":"ChromaEdge_TowerProgression","status":false,"description":"v0.1.0 Week 1 stub: Tower progression.","parameters":{}},
{"name":"ChromaEdge_EndingBranch","status":false,"description":"v0.1.0 Week 1 stub: Ending branches.","parameters":{}},
{"name":"ChromaEdge_AffinityMenu","status":false,"description":"v0.1.0 Week 1 stub: Affinity menu.","parameters":{}},
{"name":"ChromaEdge_QuestJournal","status":false,"description":"v0.1.0 Week 1 stub: Quest journal.","parameters":{}}
];
